import * as React from 'react';import {render,screen} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {axe} from 'vitest-axe';import {Button} from './Button';import {Input} from './Input';import {Select} from './Select';import {Table} from './Table';import {Dialog,DialogTrigger,DialogContent,DialogTitle} from './Dialog';import {Toast,toast} from './Toast';import {Currency,currencyFromMinor} from './Currency';import {Delta} from './Delta';import {Sparkline} from './Sparkline';import {StatusPill} from './StatusPill';import {EmptyState} from './EmptyState';import {LoadingState} from './LoadingState';

describe('Button',()=>{it.each([{name:'default',props:{}},{name:'secondary',props:{variant:'secondary' as const}},{name:'danger',props:{variant:'danger' as const}},{name:'ghost',props:{variant:'ghost' as const}},{name:'loading',props:{loading:true}},{name:'disabled',props:{disabled:true}}])('$name',async({props})=>{const u=userEvent.setup();render(<Button {...props}>Pay</Button>);const b=screen.getByRole('button');expect(b).toBeInTheDocument();if(props.loading){expect(b).toBeDisabled();expect(b).toHaveAttribute('aria-busy','true');expect(screen.getByText('Loading…')).toBeInTheDocument()}if(props.disabled)expect(b).toBeDisabled();await u.tab();if(!props.disabled&&!props.loading)expect(b).toHaveFocus();expect(b.className).toMatch(/hover:|active:/);expect(await axe(document.body)).toHaveNoViolations()})});

describe('Input',()=>{it('default, focus, disabled and error',async()=>{const u=userEvent.setup();render(<Input label="Amount" placeholder="0.00" error="Required"/>);const i=screen.getByRole('textbox');expect(i).toHaveAttribute('aria-invalid','true');expect(screen.getByRole('alert')).toHaveTextContent('Required');await u.click(i);expect(i).toHaveFocus();});it('disabled',()=>{render(<Input label="Amount" disabled/>);expect(screen.getByRole('textbox')).toBeDisabled()})});

describe('Select',()=>{it('opens, focuses, selects and exposes error/disabled states',async()=>{const u=userEvent.setup();const onChange=vi.fn();render(<Select label="Currency" options={[{value:'USD',label:'USD'},{value:'EUR',label:'EUR'},{value:'NGN',label:'NGN',disabled:true}]} error="Invalid currency" onValueChange={onChange}/>);const trigger=screen.getByRole('combobox');expect(trigger).toHaveAttribute('aria-invalid','true');await u.click(trigger);expect(screen.getByText('USD')).toBeVisible();await u.click(screen.getByText('EUR'));expect(onChange).toHaveBeenCalledWith('EUR');});it('disabled',()=>{render(<Select options={[]} disabled/>);expect(screen.getByRole('combobox')).toBeDisabled()})});

describe('Table',()=>{const data=[{id:1,name:'B',amount:20},{id:2,name:'A',amount:10}];const cols=[{key:'name',header:'Name',accessor:(r:any)=>r.name,sortValue:(r:any)=>r.name},{key:'amount',header:'Amount',accessor:(r:any)=>r.amount,sortValue:(r:any)=>r.amount,align:'right' as const}];it('renders virtual window and sorts',async()=>{const u=userEvent.setup();render(<Table data={data} columns={cols} height={120}/>);expect(screen.getByText('B')).toBeInTheDocument();await u.click(screen.getByRole('button',{name:/Name/}));expect(screen.getAllByRole('row')[1]).toHaveTextContent('A');});it('empty and clickable rows',async()=>{const onRow=vi.fn();const u=userEvent.setup();render(<Table data={[]} columns={cols} empty="Nothing"/>);expect(screen.getByText('Nothing')).toBeInTheDocument();render(<Table data={[data[0]]} columns={cols} onRowClick={onRow}/>);await u.click(screen.getByText('B'));expect(onRow).toHaveBeenCalledWith(data[0])})});

describe('Dialog',()=>{it('opens, traps focus and closes',async()=>{const u=userEvent.setup();render(<Dialog><DialogTrigger asChild><Button>Open</Button></DialogTrigger><DialogContent><DialogTitle>Settlement</DialogTitle><button>Confirm</button></DialogContent></Dialog>);await u.click(screen.getByRole('button',{name:'Open'}));expect(screen.getByRole('dialog')).toBeVisible();expect(screen.getByRole('heading',{name:'Settlement'})).toBeVisible();await u.keyboard('{Escape}');expect(screen.queryByRole('dialog')).not.toBeInTheDocument();})});

describe('Toast',()=>{it('mounts toaster and supports notifications',()=>{render(<Toast/>);expect(document.querySelector('[data-sonner-toaster]')).toBeInTheDocument();expect(typeof toast.success).toBe('function')})});

describe('Currency',()=>{it('formats domain Money exactly from minor units',()=>{const money=currencyFromMinor(12345n,'USD');render(<Currency money={money}/>);expect(screen.getByText('USD 123.45')).toBeInTheDocument()})});

describe('Delta',()=>{it.each([[5,'↑ +5'],[-5,'↓ -5'],[0,'→ 0']])('renders %s',(_,text)=>{render(<Delta value={_ as number}/>);expect(screen.getByText(text)).toBeInTheDocument()})});

describe('Sparkline',()=>{it('renders accessible SVG and empty state',()=>{const{rerender}=render(<Sparkline data={[1,3,2]} label="volume"/>);expect(screen.getByRole('img',{name:'volume'})).toBeInTheDocument();rerender(<Sparkline data={[]} label="volume"/>);expect(screen.getByRole('img',{name:'volume: no data'})).toBeInTheDocument()})});

describe('StatusPill',()=>{it.each(['pending','processing','success','failed','warning','neutral'] as const)('renders %s',status=>{render(<StatusPill status={status}/>);expect(screen.getByRole('status')).toHaveTextContent(status)})});

describe('EmptyState',()=>{it('renders content and action',()=>{render(<EmptyState title="No settlements" description="Nothing cleared yet" action={<Button>Refresh</Button>}/>);expect(screen.getByText('No settlements')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Refresh'})).toBeInTheDocument()})});

describe('LoadingState',()=>{it('renders busy loading rows',()=>{render(<LoadingState label="Loading settlements" rows={4}/>);const status=screen.getByRole('status');expect(status).toHaveAttribute('aria-busy','true');expect(status.querySelectorAll('.animate-pulse')).toHaveLength(4)})});

describe('accessibility',()=>{it('core states have no obvious violations',async()=>{render(<main><Button>Continue</Button><Input label="Account"/><StatusPill status="success"/></main>);expect(await axe(document.body)).toHaveNoViolations()})});
